DBPractice/WebPrac/Controllers/ProductController.cs
using PMS.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPrac.Security;

namespace WebPrac.Controllers
{
    public class ProductController : Controller
    {
        [HttpGet]
        public JsonResult getUserName()
        {

            Object data = null;

            try
            {
                var url = "";
                string n = "";
                int id = Convert.ToInt32(Request["id"]);
                var obj = PMS.BAL.UserBO.GetUserById(id);
                if (obj != null)
                {
                    url = Url.Content("~/Product/ShowAll");
                    n = obj.Name;

                }

                data = new
                {
                    name = n
                };
            }
            catch (Exception)
            {
                data = new
                {
                    name = ""

                };
            }

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        private ActionResult GetUrlToRedirect()
        {
            if (SessionManager.IsValidUser)
            {
                //if (SessionManager.User.IsAdmin == false)
                //{
                //    TempData["Message"] = "Unauthorized Access";
                //    return Redirect("~/Home/NormalUser");
                //}
            }
            else
            {
                TempData["Message"] = "Unauthorized Access";
                return Redirect("~/User/Login");
            }

            return null;
        }
        public ActionResult ShowAll()
        {
            if (SessionManager.IsValidUser == false)
            {
                return Redirect("~/User/Login");
            }

            var products = PMS.BAL.ProductBO.GetAllProducts(true);

            return View(products);
        }

        public ActionResult New()
        {
            var redVal = GetUrlToRedirect();
            if (redVal == null)
            {
                TempData["required"] = "required";
                var dto = new ProductDTO();
                redVal = View(dto);
            }

            return redVal;
        }

        public ActionResult Edit(int id)
        {
            if (WebPrac.Security.SessionManager.User != null)
            {
                var redVal = GetUrlToRedirect();
                ProductDTO p = PMS.BAL.ProductBO.GetProductById(id);

                if (p.CreatedBy == SessionManager.User.UserID || SessionManager.User.IsAdmin == true)
                {
                    var prod = PMS.BAL.ProductBO.GetProductById(id);
                    redVal = View("New", prod);
                }
                else
                {
                    TempData["Msg"] = "Unauthorized access";
                    TempData["required"] = "";
                    return RedirectToAction("ShowAll");
                }

                return redVal;
            }
            else
                return Redirect("~/User/Login");

        }
        public ActionResult SaveComment(string txtComment, int prodID)
        {
            if (WebPrac.Security.SessionManager.User != null)
            {
                if (txtComment != "")
                {
                    CommentDTO cm = new CommentDTO();
                    cm.UserID = SessionManager.User.UserID;
                    cm.UserName = SessionManager.User.Name;
                    cm.PictureName = SessionManager.User.PictureName;
                    cm.CommentOn = DateTime.Now;
                    cm.CommentText = txtComment;
                    cm.ProductID = prodID;
                    if (PMS.BAL.CommentBO.Save(cm) != 0)
                    {
                        return RedirectToAction("ShowAll");
                    }
                }
                else
                {
                    TempData["Msg"] = "Please enter some text";
                    

                }
                return RedirectToAction("ShowAll");

            }
            else
                Redirect("~/User/Login");
            return RedirectToAction("ShowAll");
        }
        public ActionResult Delete(int id)
        {
            if (WebPrac.Security.SessionManager.User != null)
            {
                ProductDTO p = PMS.BAL.ProductBO.GetProductById(id);
                if (p.CreatedBy == SessionManager.User.UserID || SessionManager.User.IsAdmin == true)
                {

                    PMS.BAL.ProductBO.DeleteProduct(id);
                    TempData["Msg"] = "Record is deleted!";
                    return RedirectToAction("ShowAll");
                }
                else
                {
                    TempData["Msg"] = "Unauthorized access";
                    return RedirectToAction("ShowAll");
                }
            }
            else
                return Redirect("~/User/Login");

        }
        [HttpPost]
        public ActionResult Save(ProductDTO dto)
        {

            if (dto.Name == "" || dto.Price==0 || dto.Price<0)
            {
                TempData["Msg"] = "Fill all the fields";
                return View("New",new ProductDTO());
            }


            if (SessionManager.IsValidUser)
            {

                var uniqueName = "";

                if (Request.Files["Image"] != null)
                {
                    var file = Request.Files["Image"];
                    if (file.FileName != "")
                    {
                        var ext = System.IO.Path.GetExtension(file.FileName);

                        //Generate a unique name using Guid
                        uniqueName = Guid.NewGuid().ToString() + ext;

                        //Get physical path of our folder where we want to save images
                        var rootPath = Server.MapPath("~/UploadedFiles");

                        var fileSavePath = System.IO.Path.Combine(rootPath, uniqueName);

                        // Save the uploaded file to "UploadedFiles" folder
                        file.SaveAs(fileSavePath);

                        dto.PictureName = uniqueName;
                    }
                }



                if (dto.ProductID > 0)
                {
                    dto.ModifiedOn = DateTime.Now;
                    // dto.ModifiedBy = 1;   // error fixed
                    dto.ModifiedBy = SessionManager.User.UserID;
                }
                else
                {
                    dto.CreatedOn = DateTime.Now;
                    // dto.CreatedBy = 1;   // error fixed
                    dto.CreatedBy = SessionManager.User.UserID;
                }

                PMS.BAL.ProductBO.Save(dto);

                TempData["Msg"] = "Record is saved!";

                return RedirectToAction("ShowAll");
            }
            else
            {
                return Redirect("~/User/Login");
            }


          
        }
        public ActionResult ShowProfile(int uid)
        {
            if (WebPrac.Security.SessionManager.User != null)
            {
                UserDTO udto = PMS.BAL.UserBO.GetUserById(uid);
                if (udto != null)
                {
                    return View("ShowProfile", udto);
                }
                return RedirectToAction("ShowAll");
            }
            else
                return Redirect("~/User/Login");

          
        }

    }
}

DBPractice/WebPrac/Controllers/UserController.cs
using PMS.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPrac.Security;
using PMS.BAL;
namespace WebPrac.Controllers
{
    public class UserController : Controller
    {
        private static string code;
        Random r = new Random();

        public ActionResult Code()
        {
            if (Session["resetPressed"] != null)
            {
                ViewBag.MSG = "Enter the code here";
                ViewBag.login = Session["login"];
                return View();
            }
            else
                return RedirectToAction("Login");
        }     
        [HttpPost]
        [ActionName("Code")]
        public ActionResult Code2()
        {
            if (Request["codeBtn"] != null)
            {
                string abc = Request["code"];
                if (abc == code.ToString())
                {
                    ViewBag.login = Request["login"];
                    return View("Reset");
                }
                else
                    ViewBag.MSG = "You've entered wrong code";
            }

            return View();
        }
        public ActionResult Reset()
        {
            if (Session["resetPressed"] != null)
            {
               
                ViewBag.login = Session["login"];
                Session["resetPressed"] = null;
                return View();
            }
            else
                return RedirectToAction("Login");
        }

        [HttpPost]
        [ActionName("Reset")]
        public ActionResult Reset2()
        {
            if (Request["change"] != null)
            {

                string login = Request["login"];
                UserDTO u = UserBO.GetUserByLogin(login);
                u.Login = login;
                u.Password = Request["password"];
                if (UserBO.UpdatePassword(u)!=0)
                {
                    ViewBag.username = u.Name;
                    ViewBag.img = u.PictureName;
                    ViewBag.login = u.Login;
                    SessionManager.User = u;
                    if (u.IsAdmin == false)
                    {
                        return Redirect("~/Home/NormalUser");
                    }
                    else
                    {
                        return Redirect("~/Home/Admin");
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult ChangePass()
        {
            if(Request["back"]!=null)
            {
                ViewBag.back = Request["back"];
            }
            return View();
        }
        [HttpPost]
        [ActionName("ChangePass")]
        public ActionResult ChangePass2()
        {
            if(Request["changepass"]!=null)
            {
                UserDTO u = UserBO.GetUserByLogin(SessionManager.User.Login);
                string oldpass = Request["oldpass"];
                string newpass = Request["newpass"];
                if(oldpass==u.Password)
                {
                    u.Password = newpass;
                    UserBO.UpdatePassword(u);
                    if (u.IsAdmin)
                      return   Redirect("~/Home/Admin");
                    else
                      return   Redirect("~/Home/NormalUser");

                }
                else
                {
                    ViewBag.error = "Enter correct old password please!";
                    return View();
                }
                
            }
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(String login, String password)
        {
            if (Request["btnLogin"] == "Reset Password")
            {
                if (Request["login"] != null)
                {
                    Session["resetPressed"] = "true";
                    string Email = Request["email"];
                    string l = Request["login"];
                    string subject = "ResetPassword";
                   
                    code = r.Next(1000, 10000).ToString(); // 4 digit password
                    string body = code;
                    if (UserBO.sendEmail(Email, subject, body))
                    {
                        ViewBag.login = l;
                        Session["login"] = l;
                        return RedirectToAction("Code");
                    }
                }
                else
                {
                    ViewBag.error = "Enter login for which you want to reset password!";
                    return View();
                }
            }
            else if (Request["btnLogin"] == "Login")
            {
                if(Request["login"]==null || Request["password"]==null)
                {
                    ViewBag.error = "Enter all fields plz";
                    return View();
                }
                var obj = PMS.BAL.UserBO.ValidateUser(login, password);
                if (obj != null)
                {

                    if (obj.IsAdmin == true)
                    {
                        ViewBag.login = obj.Login;
                        SessionManager.User = obj;
                        return Redirect("~/Home/Admin");
                    }

                    else
                    {
                        ViewBag.login = obj.Login;
                        SessionManager.User = obj;
                        return Redirect("~/Home/NormalUser");
                    }

                }

                ViewBag.MSG = "Invalid Login/Password";
                ViewBag.Login = login;

               
            }
            return View();
        }
        [HttpGet]
        public ActionResult NewUser()
        {

            return View();
        }

        [HttpGet]
        public ActionResult Edit()
        {
            if (Request["edit"] != null)
            {
                ViewBag.id = Request["id"];
                ViewBag.img = Request["image"];
                ViewBag.name = Request["name"];
                ViewBag.login = Request["login"];

            }
            else
                ViewBag.error = "Try Again";
            return View();

        }
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult Edit2()
        {
            if (Request["edit"] == "Save Changes")
            {

                // validation ends
                UserDTO l = UserBO.GetUserByLogin(Request["login"]);
                UserDTO u = new UserDTO();
                if (l != null)
                {
                    u.IsAdmin = l.IsAdmin;
                    u.PictureName = l.PictureName;
                    u.UserID = l.UserID;
                }

                u.Login = Request["login"];
                var file = Request.Files["filename"];

                if (file.FileName != "")
                {
                    u.PictureName = file.FileName;
                    var rootPath = Server.MapPath("~/userPics");
                    var fileSavePath = System.IO.Path.Combine(rootPath, u.PictureName);
                    file.SaveAs(fileSavePath);
                }

                u.Name = Request["name"];
                u.Password = Request["password"];
                int choice = UserBO.Save(u);
                if (choice != 0)
                {
                    if (WebPrac.Security.SessionManager.User.IsAdmin)
                    {
                        ViewBag.username = u.Name;
                        ViewBag.img = u.PictureName;
                        ViewBag.login = u.Login;
                        SessionManager.User = u;
                        return Redirect("~/Home/Admin");
                    }
                    else
                    {
                      
                        ViewBag.username = u.Name;
                        ViewBag.img = u.PictureName;
                        ViewBag.login = u.Login;
                        SessionManager.User = u;
                        return Redirect("~/Home/NormalUser");
                    }

                }
                else
                {
                    ViewBag.error = "Try Again!";
                   
                }              
            }
            return View();
        }
        [HttpPost]
        [ActionName("NewUser")]
        public ActionResult NewUser2()
        {
            // validation
            if (Request["create"] == "Sign Up")
            {

                if (Request["name"] == null || Request["password"] == null || Request["login"] == null)
                {
                   
                    ViewBag.error = "Enter all fields please!";
                    return View();
                }
               
            
                // validation ends
                UserDTO u = new UserDTO();
                u.Login= Request["login"];
                var file = Request.Files["filename"];

                if (file.FileName != "")
                {
                    u.PictureName = file.FileName;
                    var rootPath = Server.MapPath("~/userPics");
                    var fileSavePath = System.IO.Path.Combine(rootPath, u.PictureName);
                    file.SaveAs(fileSavePath);
                }
                else
                {
                   
                    ViewBag.error = "Upload some picture too!";
                    return View();
                }
                u.Name = Request["name"];
                u.Password = Request["password"];

                
                UserDTO a = UserBO.GetUserByLogin(u.Login);
                if(a!=null)
                {
                 
                    ViewBag.error = "User Already Exists";
                    return View();
                }
                int choice = UserBO.Save(u);
                if (choice == 1)

DBPractice/WebPrac/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", false);
</head>
<body >
    <div class=" navbar-inverse navbar-fixed-top" style="background-color:darkmagenta;">
        <div class="container" >
            <div class="navbar-header">
               
                @if (WebPrac.Security.SessionManager.User.IsAdmin)
                {
                   
                    @Html.ActionLink("Home", "Admin", "Home", null, new { @class = "navbar-brand" })
                  
                }
                else
                {
                    @Html.ActionLink("Home", "NormalUser", "Home", null, new { @class = "navbar-brand" })
                }
               
              
            </div>
            <div class="navbar-collapse collapse" >
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Show All", "ShowAll", "Product")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
       
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DBPractice/WebPrac/Views/Shared/_MyProductLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        .menu a {
            padding: 5px;
            background-color: lightgrey;
            color: red;
        }

        .prodbox {
            padding: 5px;
            margin: 5px;
            width: 400px;
            background-color: lightgray;
        }

        .comments .comment .picture {
            float: left;
        }

            .comments .comment .picture img {
                width: 30px;
                height: 30px;
            }

        .comments .comment .name {
            color: red;
        }

        .comments .comment .comment-text {
            font-family: Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    </style>
    <script>
        window.BasePath = '@Url.Content("~")';
    </script>

    @Styles.Render("~/Content/css")

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/MyAppGlobal.js"></script>

    @RenderSection("scripts", false)

</head>
<body>
    <div id="overlay" class="overlay">

    </div>

    <div class="menu">
        @if (WebPrac.Security.SessionManager.User.IsAdmin)
        {
            <a href="/Home/Admin">Home</a>
            <a href="/Product/ShowAll">Show All</a>
            @*<a href="/Product/New">New Product</a>*@
        }
        else
        {
            <a href="/Home/NormalUser">Home</a>
            <a href="/Product/ShowAll">Show All</a>
        }

        <a href="/User/Logout">Logout</a>
        <a href="/Product2/New">Products-AJAX</a>
    </div>

    <h1> Welcome @WebPrac.Security.SessionManager.User.Name</h1>
    <span style="color:red">@TempData["Message"]</span>
    <div>
        @RenderBody()
    </div>
</body>
</html>

DBPractice/WebPrac/Views/Shared/_MyPublicLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/mystyle.css")
    @RenderSection("css", false)
    @RenderSection("scripts",false)
</head>
<body>
    <span style="color:red">@TempData["Message"]</span>
    <div> 
        @RenderBody()
    </div>
</body>
</html>

DBPractice/WebPrac/Views/Shared/_SampleLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_SampleLayout</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    @RenderSection("scripts",false)
</head>
<body>
    <div> 
        @RenderBody()
    </div>
</body>
</html>